### Notebook for creation of features

Addition of 60 features...


NOTE THAT ANY MEANS CANT BE DONE?? OR IF SO HAVE TO BE RECALCULATED AT CV cus otherwise will have the info "in" the col

##### Read in the master df

In [10]:
import pandas as pd
import numpy as np

master_df = pd.read_csv("../Data/master_df.csv")

# drops the unnamed col... 
master_df = master_df.drop(columns=['Unnamed: 0'])

# print out a list of all the cols
print(list(master_df.columns))

master_df.head()

['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value', 'seller_zip_code_prefix', 'seller_city', 'seller_state', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm', 'product_category_name_english', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value', 'review_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp', 'customer_lat', 'customer_lng', 'seller_lat', 'seller_lng']

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,customer_lat,customer_lng,seller_lat,seller_lng
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,a54f0611adc9ed256b57ede6b6eb5114,4.0,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48,-23.576983,-46.587161,-23.680729,-46.444238
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,a54f0611adc9ed256b57ede6b6eb5114,4.0,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48,-23.576983,-46.587161,-23.680729,-46.444238
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,a54f0611adc9ed256b57ede6b6eb5114,4.0,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48,-23.576983,-46.587161,-23.680729,-46.444238
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,af07308b275d755c9edb36a90c618231,47813,...,8d5266042046a06655c8db133d120ba5,4.0,Muito boa a loja,Muito bom o produto.,2018-08-08 00:00:00,2018-08-08 18:37:50,-12.177924,-44.660711,-19.807681,-43.980427
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,e73b67b67587f7644d5bd1a52deb1b01,5.0,NaN,NaN,2018-08-18 00:00:00,2018-08-22 19:07:58,-16.745150,-48.514783,-21.363502,-48.229601

##### Bit of Cleaning

In [11]:
# 
master_df['product_name_length']  = master_df['product_name_lenght']        
master_df['product_desc_length']  = master_df['product_description_lenght']


master_df.drop(columns=['product_description_lenght', 'product_name_lenght'])

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,customer_lat,customer_lng,seller_lat,seller_lng,product_name_length,product_desc_length
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48,-23.576983,-46.587161,-23.680729,-46.444238,40.0,268.0
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48,-23.576983,-46.587161,-23.680729,-46.444238,40.0,268.0
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48,-23.576983,-46.587161,-23.680729,-46.444238,40.0,268.0
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,af07308b275d755c9edb36a90c618231,47813,...,Muito boa a loja,Muito bom o produto.,2018-08-08 00:00:00,2018-08-08 18:37:50,-12.177924,-44.660711,-19.807681,-43.980427,29.0,178.0
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,NaN,NaN,2018-08-18 00:00:00,2018-08-22 19:07:58,-16.745150,-48.514783,-21.363502,-48.229601,46.0,232.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119138,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00,da62f9e57a76d978d02ab5362c509660,11722,...,NaN,So uma peça que veio rachado mas tudo bem rs,2018-03-01 00:00:00,2018-03-02 17:50:01,-24.001500,-46.449864,-21.930548,-50.498348,52.0,828.0
119139,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00,737520a9aad80b3fbbdad19b66b37b30,45920,...,NaN,Foi entregue antes do prazo.,2017-09-22 00:00:00,2017-09-22 23:10:57,-17.898358,-39.373630,-23.553642,-46.452661,51.0,500.0
119140,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,5097a5312c8b157bb7be58ae360ef43c,28685,...,NaN,Foi entregue somente 1. Quero saber do outro p...,2018-01-26 00:00:00,2018-01-27 09:16:56,-22.562825,-42.694574,-20.940578,-45.827237,59.0,1893.0
119141,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,5097a5312c8b157bb7be58ae360ef43c,28685,...,NaN,Foi entregue somente 1. Quero saber do outro p...,2018-01-26 00:00:00,2018-01-27 09:16:56,-22.562825,-42.694574,-20.940578,-45.827237,59.0,1893.0
119142,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00,60350aa974b26ff12caad89e55993bd6,83750,...,NaN,NaN,2018-03-17 00:00:00,2018-03-17 16:33:31,-25.764308,-49.720376,-20.496251,-47.418434,45.0,569.0

##### Haversine Distance (distance between two points given long and lat)

In [ ]:
def haversine(lat1, lon1, lat2, lon2):
    R = 6371
    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])

    a = np.sin((lat2-lat1)/2)**2 + np.cos(lat1)*np.cos(lat2)*np.sin((lon2-lon1)/2)**2

    return R * 2 * np.arcsin(np.sqrt(a))

master_df['geo_distance_km'] = haversine(
    master_df['seller_lat'], master_df['seller_lng'],
    master_df['customer_lat'], master_df['customer_lng']
)

##### Datetime cols convert to datetime

In [12]:
date_time_cols = [
    'order_purchase_timestamp',
    'order_approved_at',
    'order_delivered_carrier_date',
    'order_delivered_customer_date',
    'order_estimated_delivery_date',
    'shipping_limit_date',
    'review_creation_date',
    'review_answer_timestamp',
]
for col in date_time_cols:
    master_df[col] = pd.to_datetime(master_df[col], errors='coerce')

##### Feature Construction Time Related

86400 seconds in a day, will be taking the total seconds and dividing...

- delivery_delay_days
-

In [ ]:
# delivery delay 
master_df['delivery_delay_days'] = (
    master_df['order_delivered_customer_date'] - master_df['order_estimated_delivery_date']
).dt.total_seconds() / (86400)

# how long delivery took from purchase 
master_df['end_to_end_delivery_days'] = (
    master_df['order_delivered_customer_date'] - master_df['order_purchase_timestamp']
).dt.total_seconds() / 86400

# Estimated delivery days
master_df['estimated_delivery_days'] = (
    master_df['order_estimated_delivery_date'] - master_df['order_purchase_timestamp']
).dt.total_seconds() / 86400

# Ratio of actual / estimated delivery days (pos means bad, neg means good) pos = longer to take than they said...
master_df['delivery_ratio'] = (
    master_df['end_to_end_delivery_days'] / master_df['estimated_delivery_days']
)

# Approval time... 
master_df['processing_time_hrs'] = (
    master_df['order_approved_at'] - master_df['order_purchase_timestamp']
).dt.total_seconds() / 3600


# --- 3h. days from delivery to review (how fast did they review?) ---
master_df['days_to_review'] = (
    master_df['review_creation_date'] - master_df['order_delivered_customer_date']
).dt.total_seconds() / 86400

# Calendar features ---
master_df['purchase_hour']  = master_df['order_purchase_timestamp'].dt.hour
master_df['purchase_dow']   = master_df['order_purchase_timestamp'].dt.dayofweek   
master_df['purchase_month'] = master_df['order_purchase_timestamp'].dt.month
master_df['is_weekend']     = (master_df['purchase_dow'] >= 5).astype(int)
master_df['is_night_purchase'] = master_df['purchase_hour'].between(22, 5).astype(int)  

# shipping limit proximity (did seller ship close to the deadline lower means closer to the deadline
master_df['days_before_ship_limit'] = (
    master_df['shipping_limit_date'] - master_df['order_delivered_carrier_date']
).dt.total_seconds() / 86400

##### Freight & pricing features

In [14]:
# How much of the price is delivery...
master_df['freight_ratio'] = (
    master_df['freight_value'] / (master_df['price'] + master_df['freight_value'])
)

##### Product features

In [15]:

# Has description / has photos flags 
master_df['has_description'] = (master_df['product_desc_length'] > 0).astype(int)
master_df['has_photos']      = (master_df['product_photos_qty'] > 0).astype(int)
master_df['photo_qty']       = master_df['product_photos_qty'].fillna(0)

In [ ]:
len(master_df.columns)

61

##### Miscellanous Features...

In [18]:
master_df['is_intrastate'] = (master_df['seller_state'] == master_df['customer_state']).astype(int)